/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#4059aa',
        'inverse-surface': '#2d3133',
        'surface-container-lowest': '#ffffff',
        'on-background': '#191c1e',
        'primary-fixed': '#dce1ff',
        'inverse-on-surface': '#eff1f3',
        'surface-variant': '#e0e3e5',
        'on-primary-fixed-variant': '#264191',
        'outline': '#757682',
        'secondary-fixed': '#bff365',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#a4acc5',
        'surface-container-high': '#e6e8ea',
        'surface-container-low': '#f2f4f6',
        'on-surface-variant': '#444651',
        'primary-fixed-dim': '#b6c4ff',
        'on-tertiary-fixed': '#131b2e',
        'surface-container-highest': '#e0e3e5',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#dae2fd',
        'tertiary': '#222a3e',
        'tertiary-fixed-dim': '#bec6e0',
        'secondary-fixed-dim': '#a4d64c',
        'error-container': '#ffdad6',
        'on-primary-container': '#90a8ff',
        'on-tertiary-fixed-variant': '#3f465c',
        'on-secondary-fixed': '#131f00',
        'secondary-container': '#bcf063',
        'primary-container': '#1e3a8a',
        'primary': '#00236f',
        'on-surface': '#191c1e',
        'error': '#ba1a1a',
        'secondary': '#476800',
        'surface-container': '#eceef0',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00164e',
        'on-secondary-container': '#4b6d00',
        'inverse-primary': '#b6c4ff',
        'outline-variant': '#c5c5d3',
        'on-tertiary': '#ffffff',
        'surface': '#f7f9fb',
        'on-error': '#ffffff',
        'surface-bright': '#f7f9fb',
        'tertiary-container': '#384055',
        'background': '#f7f9fb',
        'on-secondary-fixed-variant': '#354e00',
        'surface-dim': '#d8dadc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        base_unit: '8px',
        card_gap: '24px',
        container_padding: '24px',
        rail_width: '80px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'title-lg': ['Space Grotesk', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '500' }],
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
