services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    network_mode: host
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    network_mode: host
    restart: unless-stopped
    depends_on:
      - backend
