worker_processes  1;
events { worker_connections 1024; }
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    gzip on;
    gzip_types text/plain application/json application/javascript text/css;
    server {
        listen 3000;
        root   C:/campusflow/frontend;
        index  index.html;
        charset utf-8;
        location /api/ {
            proxy_pass         http://127.0.0.1:8080;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_read_timeout 120s;
        }
        location /assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "no-cache, no-store, must-revalidate" always;
            add_header Pragma "no-cache" always;
            expires 0;
        }
    }
}
